<?php

declare(strict_types=1);

namespace AndyDefer\PhpVo\Enums;

/**
 * Enum representing telephone country codes (ITU-T E.164) with ISO 3166-1 alpha-2 keys.
 *
 * @example
 * // Get telephone code by country
 * $code = TelephoneCode::FR;
 *
 * // Get telephone code value
 * echo $code->value; // "33"
 *
 * // Get formatted telephone code
 * echo '+' . $code->value; // "+33"
 *
 * // Get display name
 * echo $code->getDisplayName(); // "France (+33)"
 *
 * // From alpha-2 key
 * $code = TelephoneCode::tryFromName('CD'); // TelephoneCode::CD
 */
enum CallingCode: string
{
    case AF = '93';
    case AX = '358';
    case AL = '355';
    case DZ = '213';
    case AS = '1684';
    case AD = '376';
    case AO = '244';
    case AI = '1264';
    case AQ = '672';
    case AG = '1268';
    case AR = '54';
    case AM = '374';
    case AW = '297';
    case AU = '61';
    case AT = '43';
    case AZ = '994';
    case BS = '1242';
    case BH = '973';
    case BD = '880';
    case BB = '1246';
    case BY = '375';
    case BE = '32';
    case BZ = '501';
    case BJ = '229';
    case BM = '1441';
    case BT = '975';
    case BO = '591';
    case BQ = '599';
    case BA = '387';
    case BW = '267';
    case BV = '47';
    case BR = '55';
    case IO = '246';
    case BN = '673';
    case BG = '359';
    case BF = '226';
    case BI = '257';
    case CV = '238';
    case KH = '855';
    case CM = '237';
    case CA = '1';
    case KY = '1345';
    case CF = '236';
    case TD = '235';
    case CL = '56';
    case CN = '86';
    case CX = '61';
    case CC = '61';
    case CO = '57';
    case KM = '269';
    case CG = '242';
    case CD = '243';
    case CK = '682';
    case CR = '506';
    case CI = '225';
    case HR = '385';
    case CU = '53';
    case CW = '599';
    case CY = '357';
    case CZ = '420';
    case DK = '45';
    case DJ = '253';
    case DM = '1767';
    case DO = '1809';
    case EC = '593';
    case EG = '20';
    case SV = '503';
    case GQ = '240';
    case ER = '291';
    case EE = '372';
    case SZ = '268';
    case ET = '251';
    case FK = '500';
    case FO = '298';
    case FJ = '679';
    case FI = '358';
    case FR = '33';
    case GF = '594';
    case PF = '689';
    case TF = '262';
    case GA = '241';
    case GM = '220';
    case GE = '995';
    case DE = '49';
    case GH = '233';
    case GI = '350';
    case GR = '30';
    case GL = '299';
    case GD = '1473';
    case GP = '590';
    case GU = '1671';
    case GT = '502';
    case GG = '44';
    case GN = '224';
    case GW = '245';
    case GY = '592';
    case HT = '509';
    case HM = '672';
    case VA = '39';
    case HN = '504';
    case HK = '852';
    case HU = '36';
    case IS = '354';
    case IN = '91';
    case ID = '62';
    case IR = '98';
    case IQ = '964';
    case IE = '353';
    case IM = '44';
    case IL = '972';
    case IT = '39';
    case JM = '1876';
    case JP = '81';
    case JE = '44';
    case JO = '962';
    case KZ = '7';
    case KE = '254';
    case KI = '686';
    case KP = '850';
    case KR = '82';
    case KW = '965';
    case KG = '996';
    case LA = '856';
    case LV = '371';
    case LB = '961';
    case LS = '266';
    case LR = '231';
    case LY = '218';
    case LI = '423';
    case LT = '370';
    case LU = '352';
    case MO = '853';
    case MG = '261';
    case MW = '265';
    case MY = '60';
    case MV = '960';
    case ML = '223';
    case MT = '356';
    case MH = '692';
    case MQ = '596';
    case MR = '222';
    case MU = '230';
    case YT = '262';
    case MX = '52';
    case FM = '691';
    case MD = '373';
    case MC = '377';
    case MN = '976';
    case ME = '382';
    case MS = '1664';
    case MA = '212';
    case MZ = '258';
    case MM = '95';
    case NA = '264';
    case NR = '674';
    case NP = '977';
    case NL = '31';
    case NC = '687';
    case NZ = '64';
    case NI = '505';
    case NE = '227';
    case NG = '234';
    case NU = '683';
    case NF = '672';
    case MK = '389';
    case MP = '1670';
    case NO = '47';
    case OM = '968';
    case PK = '92';
    case PW = '680';
    case PS = '970';
    case PA = '507';
    case PG = '675';
    case PY = '595';
    case PE = '51';
    case PH = '63';
    case PN = '870';
    case PL = '48';
    case PT = '351';
    case PR = '1787';
    case QA = '974';
    case RE = '262';
    case RO = '40';
    case RU = '7';
    case RW = '250';
    case BL = '590';
    case SH = '290';
    case KN = '1869';
    case LC = '1758';
    case MF = '590';
    case PM = '508';
    case VC = '1784';
    case WS = '685';
    case SM = '378';
    case ST = '239';
    case SA = '966';
    case SN = '221';
    case RS = '381';
    case SC = '248';
    case SL = '232';
    case SG = '65';
    case SX = '1721';
    case SK = '421';
    case SI = '386';
    case SB = '677';
    case SO = '252';
    case ZA = '27';
    case GS = '500';
    case SS = '211';
    case ES = '34';
    case LK = '94';
    case SD = '249';
    case SR = '597';
    case SJ = '47';
    case SE = '46';
    case CH = '41';
    case SY = '963';
    case TW = '886';
    case TJ = '992';
    case TZ = '255';
    case TH = '66';
    case TL = '670';
    case TG = '228';
    case TK = '690';
    case TO = '676';
    case TT = '1868';
    case TN = '216';
    case TR = '90';
    case TM = '993';
    case TC = '1649';
    case TV = '688';
    case UG = '256';
    case UA = '380';
    case AE = '971';
    case GB = '44';
    case US = '1';
    case UM = '1';
    case UY = '598';
    case UZ = '998';
    case VU = '678';
    case VE = '58';
    case VN = '84';
    case VG = '1284';
    case VI = '1340';
    case WF = '681';
    case EH = '212';
    case YE = '967';
    case ZM = '260';
    case ZW = '263';

    /**
     * Get the display name with country name and telephone code.
     */
    public function getDisplayName(): string
    {
        return match ($this) {
            self::AF => 'Afghanistan (+93)',
            self::AX => 'Åland Islands (+358)',
            self::AL => 'Albania (+355)',
            self::DZ => 'Algeria (+213)',
            self::AS => 'American Samoa (+1684)',
            self::AD => 'Andorra (+376)',
            self::AO => 'Angola (+244)',
            self::AI => 'Anguilla (+1264)',
            self::AQ => 'Antarctica (+672)',
            self::AG => 'Antigua and Barbuda (+1268)',
            self::AR => 'Argentina (+54)',
            self::AM => 'Armenia (+374)',
            self::AW => 'Aruba (+297)',
            self::AU => 'Australia (+61)',
            self::AT => 'Austria (+43)',
            self::AZ => 'Azerbaijan (+994)',
            self::BS => 'Bahamas (+1242)',
            self::BH => 'Bahrain (+973)',
            self::BD => 'Bangladesh (+880)',
            self::BB => 'Barbados (+1246)',
            self::BY => 'Belarus (+375)',
            self::BE => 'Belgium (+32)',
            self::BZ => 'Belize (+501)',
            self::BJ => 'Benin (+229)',
            self::BM => 'Bermuda (+1441)',
            self::BT => 'Bhutan (+975)',
            self::BO => 'Bolivia (+591)',
            self::BQ => 'Bonaire, Sint Eustatius and Saba (+599)',
            self::BA => 'Bosnia and Herzegovina (+387)',
            self::BW => 'Botswana (+267)',
            self::BV => 'Bouvet Island (+47)',
            self::BR => 'Brazil (+55)',
            self::IO => 'British Indian Ocean Territory (+246)',
            self::BN => 'Brunei Darussalam (+673)',
            self::BG => 'Bulgaria (+359)',
            self::BF => 'Burkina Faso (+226)',
            self::BI => 'Burundi (+257)',
            self::CV => 'Cabo Verde (+238)',
            self::KH => 'Cambodia (+855)',
            self::CM => 'Cameroon (+237)',
            self::CA => 'Canada (+1)',
            self::KY => 'Cayman Islands (+1345)',
            self::CF => 'Central African Republic (+236)',
            self::TD => 'Chad (+235)',
            self::CL => 'Chile (+56)',
            self::CN => 'China (+86)',
            self::CX => 'Christmas Island (+61)',
            self::CC => 'Cocos (Keeling) Islands (+61)',
            self::CO => 'Colombia (+57)',
            self::KM => 'Comoros (+269)',
            self::CG => 'Congo (+242)',
            self::CD => 'Congo (Democratic Republic of the) (+243)',
            self::CK => 'Cook Islands (+682)',
            self::CR => 'Costa Rica (+506)',
            self::CI => 'Côte d\'Ivoire (+225)',
            self::HR => 'Croatia (+385)',
            self::CU => 'Cuba (+53)',
            self::CW => 'Curaçao (+599)',
            self::CY => 'Cyprus (+357)',
            self::CZ => 'Czechia (+420)',
            self::DK => 'Denmark (+45)',
            self::DJ => 'Djibouti (+253)',
            self::DM => 'Dominica (+1767)',
            self::DO => 'Dominican Republic (+1809)',
            self::EC => 'Ecuador (+593)',
            self::EG => 'Egypt (+20)',
            self::SV => 'El Salvador (+503)',
            self::GQ => 'Equatorial Guinea (+240)',
            self::ER => 'Eritrea (+291)',
            self::EE => 'Estonia (+372)',
            self::SZ => 'Eswatini (+268)',
            self::ET => 'Ethiopia (+251)',
            self::FK => 'Falkland Islands (+500)',
            self::FO => 'Faroe Islands (+298)',
            self::FJ => 'Fiji (+679)',
            self::FI => 'Finland (+358)',
            self::FR => 'France (+33)',
            self::GF => 'French Guiana (+594)',
            self::PF => 'French Polynesia (+689)',
            self::TF => 'French Southern Territories (+262)',
            self::GA => 'Gabon (+241)',
            self::GM => 'Gambia (+220)',
            self::GE => 'Georgia (+995)',
            self::DE => 'Germany (+49)',
            self::GH => 'Ghana (+233)',
            self::GI => 'Gibraltar (+350)',
            self::GR => 'Greece (+30)',
            self::GL => 'Greenland (+299)',
            self::GD => 'Grenada (+1473)',
            self::GP => 'Guadeloupe (+590)',
            self::GU => 'Guam (+1671)',
            self::GT => 'Guatemala (+502)',
            self::GG => 'Guernsey (+44)',
            self::GN => 'Guinea (+224)',
            self::GW => 'Guinea-Bissau (+245)',
            self::GY => 'Guyana (+592)',
            self::HT => 'Haiti (+509)',
            self::HM => 'Heard Island and McDonald Islands (+672)',
            self::VA => 'Holy See (+39)',
            self::HN => 'Honduras (+504)',
            self::HK => 'Hong Kong (+852)',
            self::HU => 'Hungary (+36)',
            self::IS => 'Iceland (+354)',
            self::IN => 'India (+91)',
            self::ID => 'Indonesia (+62)',
            self::IR => 'Iran (+98)',
            self::IQ => 'Iraq (+964)',
            self::IE => 'Ireland (+353)',
            self::IM => 'Isle of Man (+44)',
            self::IL => 'Israel (+972)',
            self::IT => 'Italy (+39)',
            self::JM => 'Jamaica (+1876)',
            self::JP => 'Japan (+81)',
            self::JE => 'Jersey (+44)',
            self::JO => 'Jordan (+962)',
            self::KZ => 'Kazakhstan (+7)',
            self::KE => 'Kenya (+254)',
            self::KI => 'Kiribati (+686)',
            self::KP => 'North Korea (+850)',
            self::KR => 'South Korea (+82)',
            self::KW => 'Kuwait (+965)',
            self::KG => 'Kyrgyzstan (+996)',
            self::LA => 'Laos (+856)',
            self::LV => 'Latvia (+371)',
            self::LB => 'Lebanon (+961)',
            self::LS => 'Lesotho (+266)',
            self::LR => 'Liberia (+231)',
            self::LY => 'Libya (+218)',
            self::LI => 'Liechtenstein (+423)',
            self::LT => 'Lithuania (+370)',
            self::LU => 'Luxembourg (+352)',
            self::MO => 'Macao (+853)',
            self::MG => 'Madagascar (+261)',
            self::MW => 'Malawi (+265)',
            self::MY => 'Malaysia (+60)',
            self::MV => 'Maldives (+960)',
            self::ML => 'Mali (+223)',
            self::MT => 'Malta (+356)',
            self::MH => 'Marshall Islands (+692)',
            self::MQ => 'Martinique (+596)',
            self::MR => 'Mauritania (+222)',
            self::MU => 'Mauritius (+230)',
            self::YT => 'Mayotte (+262)',
            self::MX => 'Mexico (+52)',
            self::FM => 'Micronesia (+691)',
            self::MD => 'Moldova (+373)',
            self::MC => 'Monaco (+377)',
            self::MN => 'Mongolia (+976)',
            self::ME => 'Montenegro (+382)',
            self::MS => 'Montserrat (+1664)',
            self::MA => 'Morocco (+212)',
            self::MZ => 'Mozambique (+258)',
            self::MM => 'Myanmar (+95)',
            self::NA => 'Namibia (+264)',
            self::NR => 'Nauru (+674)',
            self::NP => 'Nepal (+977)',
            self::NL => 'Netherlands (+31)',
            self::NC => 'New Caledonia (+687)',
            self::NZ => 'New Zealand (+64)',
            self::NI => 'Nicaragua (+505)',
            self::NE => 'Niger (+227)',
            self::NG => 'Nigeria (+234)',
            self::NU => 'Niue (+683)',
            self::NF => 'Norfolk Island (+672)',
            self::MK => 'North Macedonia (+389)',
            self::MP => 'Northern Mariana Islands (+1670)',
            self::NO => 'Norway (+47)',
            self::OM => 'Oman (+968)',
            self::PK => 'Pakistan (+92)',
            self::PW => 'Palau (+680)',
            self::PS => 'Palestine (+970)',
            self::PA => 'Panama (+507)',
            self::PG => 'Papua New Guinea (+675)',
            self::PY => 'Paraguay (+595)',
            self::PE => 'Peru (+51)',
            self::PH => 'Philippines (+63)',
            self::PN => 'Pitcairn (+870)',
            self::PL => 'Poland (+48)',
            self::PT => 'Portugal (+351)',
            self::PR => 'Puerto Rico (+1787)',
            self::QA => 'Qatar (+974)',
            self::RE => 'Réunion (+262)',
            self::RO => 'Romania (+40)',
            self::RU => 'Russia (+7)',
            self::RW => 'Rwanda (+250)',
            self::BL => 'Saint Barthélemy (+590)',
            self::SH => 'Saint Helena (+290)',
            self::KN => 'Saint Kitts and Nevis (+1869)',
            self::LC => 'Saint Lucia (+1758)',
            self::MF => 'Saint Martin (+590)',
            self::PM => 'Saint Pierre and Miquelon (+508)',
            self::VC => 'Saint Vincent and the Grenadines (+1784)',
            self::WS => 'Samoa (+685)',
            self::SM => 'San Marino (+378)',
            self::ST => 'Sao Tome and Principe (+239)',
            self::SA => 'Saudi Arabia (+966)',
            self::SN => 'Senegal (+221)',
            self::RS => 'Serbia (+381)',
            self::SC => 'Seychelles (+248)',
            self::SL => 'Sierra Leone (+232)',
            self::SG => 'Singapore (+65)',
            self::SX => 'Sint Maarten (+1721)',
            self::SK => 'Slovakia (+421)',
            self::SI => 'Slovenia (+386)',
            self::SB => 'Solomon Islands (+677)',
            self::SO => 'Somalia (+252)',
            self::ZA => 'South Africa (+27)',
            self::GS => 'South Georgia (+500)',
            self::SS => 'South Sudan (+211)',
            self::ES => 'Spain (+34)',
            self::LK => 'Sri Lanka (+94)',
            self::SD => 'Sudan (+249)',
            self::SR => 'Suriname (+597)',
            self::SJ => 'Svalbard and Jan Mayen (+47)',
            self::SE => 'Sweden (+46)',
            self::CH => 'Switzerland (+41)',
            self::SY => 'Syria (+963)',
            self::TW => 'Taiwan (+886)',
            self::TJ => 'Tajikistan (+992)',
            self::TZ => 'Tanzania (+255)',
            self::TH => 'Thailand (+66)',
            self::TL => 'Timor-Leste (+670)',
            self::TG => 'Togo (+228)',
            self::TK => 'Tokelau (+690)',
            self::TO => 'Tonga (+676)',
            self::TT => 'Trinidad and Tobago (+1868)',
            self::TN => 'Tunisia (+216)',
            self::TR => 'Turkey (+90)',
            self::TM => 'Turkmenistan (+993)',
            self::TC => 'Turks and Caicos Islands (+1649)',
            self::TV => 'Tuvalu (+688)',
            self::UG => 'Uganda (+256)',
            self::UA => 'Ukraine (+380)',
            self::AE => 'United Arab Emirates (+971)',
            self::GB => 'United Kingdom (+44)',
            self::US => 'United States (+1)',
            self::UM => 'United States Minor Outlying Islands (+1)',
            self::UY => 'Uruguay (+598)',
            self::UZ => 'Uzbekistan (+998)',
            self::VU => 'Vanuatu (+678)',
            self::VE => 'Venezuela (+58)',
            self::VN => 'Viet Nam (+84)',
            self::VG => 'Virgin Islands (British) (+1284)',
            self::VI => 'Virgin Islands (U.S.) (+1340)',
            self::WF => 'Wallis and Futuna (+681)',
            self::EH => 'Western Sahara (+212)',
            self::YE => 'Yemen (+967)',
            self::ZM => 'Zambia (+260)',
            self::ZW => 'Zimbabwe (+263)',
        };
    }
}
