<?php

declare(strict_types=1);

namespace AndyDefer\PhpVo\Enums;

/**
 * Enum representing all countries with their ISO 3166-1 codes (alpha-2 and alpha-3).
 * 
 * @example
 * // Get country by alpha-2 code
 * $country = Country::FR;
 * 
 * // Get alpha-3 code
 * echo $country->value; // "FRA"
 * 
 * // Get alpha-2 code
 * echo $country->name; // "FR"
 * 
 * // Get display name
 * echo $country->getDisplayName(); // "France"
 * 
 * // From alpha-3 code
 * $country = Country::from('COD'); // Country::CD
 * 
 * // From alpha-2 code
 * $country = Country::tryFromName('CD'); // Country::CD
 * 
 * @package AndyDefer\PhpVo\Enums
 */
enum Country: string
{
    case AF = 'AFG';
    case AX = 'ALA';
    case AL = 'ALB';
    case DZ = 'DZA';
    case AS = 'ASM';
    case AD = 'AND';
    case AO = 'AGO';
    case AI = 'AIA';
    case AQ = 'ATA';
    case AG = 'ATG';
    case AR = 'ARG';
    case AM = 'ARM';
    case AW = 'ABW';
    case AU = 'AUS';
    case AT = 'AUT';
    case AZ = 'AZE';
    case BS = 'BHS';
    case BH = 'BHR';
    case BD = 'BGD';
    case BB = 'BRB';
    case BY = 'BLR';
    case BE = 'BEL';
    case BZ = 'BLZ';
    case BJ = 'BEN';
    case BM = 'BMU';
    case BT = 'BTN';
    case BO = 'BOL';
    case BQ = 'BES';
    case BA = 'BIH';
    case BW = 'BWA';
    case BV = 'BVT';
    case BR = 'BRA';
    case IO = 'IOT';
    case BN = 'BRN';
    case BG = 'BGR';
    case BF = 'BFA';
    case BI = 'BDI';
    case CV = 'CPV';
    case KH = 'KHM';
    case CM = 'CMR';
    case CA = 'CAN';
    case KY = 'CYM';
    case CF = 'CAF';
    case TD = 'TCD';
    case CL = 'CHL';
    case CN = 'CHN';
    case CX = 'CXR';
    case CC = 'CCK';
    case CO = 'COL';
    case KM = 'COM';
    case CG = 'COG';
    case CD = 'COD';
    case CK = 'COK';
    case CR = 'CRI';
    case CI = 'CIV';
    case HR = 'HRV';
    case CU = 'CUB';
    case CW = 'CUW';
    case CY = 'CYP';
    case CZ = 'CZE';
    case DK = 'DNK';
    case DJ = 'DJI';
    case DM = 'DMA';
    case DO = 'DOM';
    case EC = 'ECU';
    case EG = 'EGY';
    case SV = 'SLV';
    case GQ = 'GNQ';
    case ER = 'ERI';
    case EE = 'EST';
    case SZ = 'SWZ';
    case ET = 'ETH';
    case FK = 'FLK';
    case FO = 'FRO';
    case FJ = 'FJI';
    case FI = 'FIN';
    case FR = 'FRA';
    case GF = 'GUF';
    case PF = 'PYF';
    case TF = 'ATF';
    case GA = 'GAB';
    case GM = 'GMB';
    case GE = 'GEO';
    case DE = 'DEU';
    case GH = 'GHA';
    case GI = 'GIB';
    case GR = 'GRC';
    case GL = 'GRL';
    case GD = 'GRD';
    case GP = 'GLP';
    case GU = 'GUM';
    case GT = 'GTM';
    case GG = 'GGY';
    case GN = 'GIN';
    case GW = 'GNB';
    case GY = 'GUY';
    case HT = 'HTI';
    case HM = 'HMD';
    case VA = 'VAT';
    case HN = 'HND';
    case HK = 'HKG';
    case HU = 'HUN';
    case IS = 'ISL';
    case IN = 'IND';
    case ID = 'IDN';
    case IR = 'IRN';
    case IQ = 'IRQ';
    case IE = 'IRL';
    case IM = 'IMN';
    case IL = 'ISR';
    case IT = 'ITA';
    case JM = 'JAM';
    case JP = 'JPN';
    case JE = 'JEY';
    case JO = 'JOR';
    case KZ = 'KAZ';
    case KE = 'KEN';
    case KI = 'KIR';
    case KP = 'PRK';
    case KR = 'KOR';
    case KW = 'KWT';
    case KG = 'KGZ';
    case LA = 'LAO';
    case LV = 'LVA';
    case LB = 'LBN';
    case LS = 'LSO';
    case LR = 'LBR';
    case LY = 'LBY';
    case LI = 'LIE';
    case LT = 'LTU';
    case LU = 'LUX';
    case MO = 'MAC';
    case MG = 'MDG';
    case MW = 'MWI';
    case MY = 'MYS';
    case MV = 'MDV';
    case ML = 'MLI';
    case MT = 'MLT';
    case MH = 'MHL';
    case MQ = 'MTQ';
    case MR = 'MRT';
    case MU = 'MUS';
    case YT = 'MYT';
    case MX = 'MEX';
    case FM = 'FSM';
    case MD = 'MDA';
    case MC = 'MCO';
    case MN = 'MNG';
    case ME = 'MNE';
    case MS = 'MSR';
    case MA = 'MAR';
    case MZ = 'MOZ';
    case MM = 'MMR';
    case NA = 'NAM';
    case NR = 'NRU';
    case NP = 'NPL';
    case NL = 'NLD';
    case NC = 'NCL';
    case NZ = 'NZL';
    case NI = 'NIC';
    case NE = 'NER';
    case NG = 'NGA';
    case NU = 'NIU';
    case NF = 'NFK';
    case MK = 'MKD';
    case MP = 'MNP';
    case NO = 'NOR';
    case OM = 'OMN';
    case PK = 'PAK';
    case PW = 'PLW';
    case PS = 'PSE';
    case PA = 'PAN';
    case PG = 'PNG';
    case PY = 'PRY';
    case PE = 'PER';
    case PH = 'PHL';
    case PN = 'PCN';
    case PL = 'POL';
    case PT = 'PRT';
    case PR = 'PRI';
    case QA = 'QAT';
    case RE = 'REU';
    case RO = 'ROU';
    case RU = 'RUS';
    case RW = 'RWA';
    case BL = 'BLM';
    case SH = 'SHN';
    case KN = 'KNA';
    case LC = 'LCA';
    case MF = 'MAF';
    case PM = 'SPM';
    case VC = 'VCT';
    case WS = 'WSM';
    case SM = 'SMR';
    case ST = 'STP';
    case SA = 'SAU';
    case SN = 'SEN';
    case RS = 'SRB';
    case SC = 'SYC';
    case SL = 'SLE';
    case SG = 'SGP';
    case SX = 'SXM';
    case SK = 'SVK';
    case SI = 'SVN';
    case SB = 'SLB';
    case SO = 'SOM';
    case ZA = 'ZAF';
    case GS = 'SGS';
    case SS = 'SSD';
    case ES = 'ESP';
    case LK = 'LKA';
    case SD = 'SDN';
    case SR = 'SUR';
    case SJ = 'SJM';
    case SE = 'SWE';
    case CH = 'CHE';
    case SY = 'SYR';
    case TW = 'TWN';
    case TJ = 'TJK';
    case TZ = 'TZA';
    case TH = 'THA';
    case TL = 'TLS';
    case TG = 'TGO';
    case TK = 'TKL';
    case TO = 'TON';
    case TT = 'TTO';
    case TN = 'TUN';
    case TR = 'TUR';
    case TM = 'TKM';
    case TC = 'TCA';
    case TV = 'TUV';
    case UG = 'UGA';
    case UA = 'UKR';
    case AE = 'ARE';
    case GB = 'GBR';
    case US = 'USA';
    case UM = 'UMI';
    case UY = 'URY';
    case UZ = 'UZB';
    case VU = 'VUT';
    case VE = 'VEN';
    case VN = 'VNM';
    case VG = 'VGB';
    case VI = 'VIR';
    case WF = 'WLF';
    case EH = 'ESH';
    case YE = 'YEM';
    case ZM = 'ZMB';
    case ZW = 'ZWE';

    /**
     * Get the display name of the country in English.
     */
    public function getDisplayName(): string
    {
        return match ($this) {
            self::AF => 'Afghanistan',
            self::AX => 'Åland Islands',
            self::AL => 'Albania',
            self::DZ => 'Algeria',
            self::AS => 'American Samoa',
            self::AD => 'Andorra',
            self::AO => 'Angola',
            self::AI => 'Anguilla',
            self::AQ => 'Antarctica',
            self::AG => 'Antigua and Barbuda',
            self::AR => 'Argentina',
            self::AM => 'Armenia',
            self::AW => 'Aruba',
            self::AU => 'Australia',
            self::AT => 'Austria',
            self::AZ => 'Azerbaijan',
            self::BS => 'Bahamas',
            self::BH => 'Bahrain',
            self::BD => 'Bangladesh',
            self::BB => 'Barbados',
            self::BY => 'Belarus',
            self::BE => 'Belgium',
            self::BZ => 'Belize',
            self::BJ => 'Benin',
            self::BM => 'Bermuda',
            self::BT => 'Bhutan',
            self::BO => 'Bolivia (Plurinational State of)',
            self::BQ => 'Bonaire, Sint Eustatius and Saba',
            self::BA => 'Bosnia and Herzegovina',
            self::BW => 'Botswana',
            self::BV => 'Bouvet Island',
            self::BR => 'Brazil',
            self::IO => 'British Indian Ocean Territory',
            self::BN => 'Brunei Darussalam',
            self::BG => 'Bulgaria',
            self::BF => 'Burkina Faso',
            self::BI => 'Burundi',
            self::CV => 'Cabo Verde',
            self::KH => 'Cambodia',
            self::CM => 'Cameroon',
            self::CA => 'Canada',
            self::KY => 'Cayman Islands',
            self::CF => 'Central African Republic',
            self::TD => 'Chad',
            self::CL => 'Chile',
            self::CN => 'China',
            self::CX => 'Christmas Island',
            self::CC => 'Cocos (Keeling) Islands',
            self::CO => 'Colombia',
            self::KM => 'Comoros',
            self::CG => 'Congo',
            self::CD => 'Congo (Democratic Republic of the)',
            self::CK => 'Cook Islands',
            self::CR => 'Costa Rica',
            self::CI => 'Côte d\'Ivoire',
            self::HR => 'Croatia',
            self::CU => 'Cuba',
            self::CW => 'Curaçao',
            self::CY => 'Cyprus',
            self::CZ => 'Czechia',
            self::DK => 'Denmark',
            self::DJ => 'Djibouti',
            self::DM => 'Dominica',
            self::DO => 'Dominican Republic',
            self::EC => 'Ecuador',
            self::EG => 'Egypt',
            self::SV => 'El Salvador',
            self::GQ => 'Equatorial Guinea',
            self::ER => 'Eritrea',
            self::EE => 'Estonia',
            self::SZ => 'Eswatini',
            self::ET => 'Ethiopia',
            self::FK => 'Falkland Islands (Malvinas)',
            self::FO => 'Faroe Islands',
            self::FJ => 'Fiji',
            self::FI => 'Finland',
            self::FR => 'France',
            self::GF => 'French Guiana',
            self::PF => 'French Polynesia',
            self::TF => 'French Southern Territories',
            self::GA => 'Gabon',
            self::GM => 'Gambia',
            self::GE => 'Georgia',
            self::DE => 'Germany',
            self::GH => 'Ghana',
            self::GI => 'Gibraltar',
            self::GR => 'Greece',
            self::GL => 'Greenland',
            self::GD => 'Grenada',
            self::GP => 'Guadeloupe',
            self::GU => 'Guam',
            self::GT => 'Guatemala',
            self::GG => 'Guernsey',
            self::GN => 'Guinea',
            self::GW => 'Guinea-Bissau',
            self::GY => 'Guyana',
            self::HT => 'Haiti',
            self::HM => 'Heard Island and McDonald Islands',
            self::VA => 'Holy See',
            self::HN => 'Honduras',
            self::HK => 'Hong Kong',
            self::HU => 'Hungary',
            self::IS => 'Iceland',
            self::IN => 'India',
            self::ID => 'Indonesia',
            self::IR => 'Iran (Islamic Republic of)',
            self::IQ => 'Iraq',
            self::IE => 'Ireland',
            self::IM => 'Isle of Man',
            self::IL => 'Israel',
            self::IT => 'Italy',
            self::JM => 'Jamaica',
            self::JP => 'Japan',
            self::JE => 'Jersey',
            self::JO => 'Jordan',
            self::KZ => 'Kazakhstan',
            self::KE => 'Kenya',
            self::KI => 'Kiribati',
            self::KP => 'Korea (Democratic People\'s Republic of)',
            self::KR => 'Korea (Republic of)',
            self::KW => 'Kuwait',
            self::KG => 'Kyrgyzstan',
            self::LA => 'Lao People\'s Democratic Republic',
            self::LV => 'Latvia',
            self::LB => 'Lebanon',
            self::LS => 'Lesotho',
            self::LR => 'Liberia',
            self::LY => 'Libya',
            self::LI => 'Liechtenstein',
            self::LT => 'Lithuania',
            self::LU => 'Luxembourg',
            self::MO => 'Macao',
            self::MG => 'Madagascar',
            self::MW => 'Malawi',
            self::MY => 'Malaysia',
            self::MV => 'Maldives',
            self::ML => 'Mali',
            self::MT => 'Malta',
            self::MH => 'Marshall Islands',
            self::MQ => 'Martinique',
            self::MR => 'Mauritania',
            self::MU => 'Mauritius',
            self::YT => 'Mayotte',
            self::MX => 'Mexico',
            self::FM => 'Micronesia (Federated States of)',
            self::MD => 'Moldova (Republic of)',
            self::MC => 'Monaco',
            self::MN => 'Mongolia',
            self::ME => 'Montenegro',
            self::MS => 'Montserrat',
            self::MA => 'Morocco',
            self::MZ => 'Mozambique',
            self::MM => 'Myanmar',
            self::NA => 'Namibia',
            self::NR => 'Nauru',
            self::NP => 'Nepal',
            self::NL => 'Netherlands',
            self::NC => 'New Caledonia',
            self::NZ => 'New Zealand',
            self::NI => 'Nicaragua',
            self::NE => 'Niger',
            self::NG => 'Nigeria',
            self::NU => 'Niue',
            self::NF => 'Norfolk Island',
            self::MK => 'North Macedonia',
            self::MP => 'Northern Mariana Islands',
            self::NO => 'Norway',
            self::OM => 'Oman',
            self::PK => 'Pakistan',
            self::PW => 'Palau',
            self::PS => 'Palestine, State of',
            self::PA => 'Panama',
            self::PG => 'Papua New Guinea',
            self::PY => 'Paraguay',
            self::PE => 'Peru',
            self::PH => 'Philippines',
            self::PN => 'Pitcairn',
            self::PL => 'Poland',
            self::PT => 'Portugal',
            self::PR => 'Puerto Rico',
            self::QA => 'Qatar',
            self::RE => 'Réunion',
            self::RO => 'Romania',
            self::RU => 'Russian Federation',
            self::RW => 'Rwanda',
            self::BL => 'Saint Barthélemy',
            self::SH => 'Saint Helena, Ascension and Tristan da Cunha',
            self::KN => 'Saint Kitts and Nevis',
            self::LC => 'Saint Lucia',
            self::MF => 'Saint Martin (French part)',
            self::PM => 'Saint Pierre and Miquelon',
            self::VC => 'Saint Vincent and the Grenadines',
            self::WS => 'Samoa',
            self::SM => 'San Marino',
            self::ST => 'Sao Tome and Principe',
            self::SA => 'Saudi Arabia',
            self::SN => 'Senegal',
            self::RS => 'Serbia',
            self::SC => 'Seychelles',
            self::SL => 'Sierra Leone',
            self::SG => 'Singapore',
            self::SX => 'Sint Maarten (Dutch part)',
            self::SK => 'Slovakia',
            self::SI => 'Slovenia',
            self::SB => 'Solomon Islands',
            self::SO => 'Somalia',
            self::ZA => 'South Africa',
            self::GS => 'South Georgia and the South Sandwich Islands',
            self::SS => 'South Sudan',
            self::ES => 'Spain',
            self::LK => 'Sri Lanka',
            self::SD => 'Sudan',
            self::SR => 'Suriname',
            self::SJ => 'Svalbard and Jan Mayen',
            self::SE => 'Sweden',
            self::CH => 'Switzerland',
            self::SY => 'Syrian Arab Republic',
            self::TW => 'Taiwan (Province of China)',
            self::TJ => 'Tajikistan',
            self::TZ => 'Tanzania, United Republic of',
            self::TH => 'Thailand',
            self::TL => 'Timor-Leste',
            self::TG => 'Togo',
            self::TK => 'Tokelau',
            self::TO => 'Tonga',
            self::TT => 'Trinidad and Tobago',
            self::TN => 'Tunisia',
            self::TR => 'Turkiye',
            self::TM => 'Turkmenistan',
            self::TC => 'Turks and Caicos Islands',
            self::TV => 'Tuvalu',
            self::UG => 'Uganda',
            self::UA => 'Ukraine',
            self::AE => 'United Arab Emirates',
            self::GB => 'United Kingdom of Great Britain and Northern Ireland',
            self::US => 'United States of America',
            self::UM => 'United States Minor Outlying Islands',
            self::UY => 'Uruguay',
            self::UZ => 'Uzbekistan',
            self::VU => 'Vanuatu',
            self::VE => 'Venezuela (Bolivarian Republic of)',
            self::VN => 'Viet Nam',
            self::VG => 'Virgin Islands (British)',
            self::VI => 'Virgin Islands (U.S.)',
            self::WF => 'Wallis and Futuna',
            self::EH => 'Western Sahara',
            self::YE => 'Yemen',
            self::ZM => 'Zambia',
            self::ZW => 'Zimbabwe',
        };
    }
}
