<?php

declare(strict_types=1);

namespace AndyDefer\PhpVo\Enums;

/**
 * Socialite Providers Enum.
 *
 * @author Generated by Andy Defer
 */
enum SocialiteProvider: string
{
    // Officiels (supportés nativement par Laravel Socialite)
    case FACEBOOK = 'facebook';
    case TWITTER = 'twitter';
    case GOOGLE = 'google';
    case LINKEDIN = 'linkedin';
    case GITHUB = 'github';
    case GITLAB = 'gitlab';
    case BITBUCKET = 'bitbucket';
    case SLACK = 'slack';
    case TWITCH = 'twitch';

    /**
     * Get the provider driver name.
     */
    public function getDriverName(): string
    {
        return $this->value;
    }

    /**
     * Get the display name for the provider.
     */
    public function getDisplayName(): string
    {
        return match ($this) {
            self::FACEBOOK => 'Facebook',
            self::TWITTER => 'Twitter',
            self::GOOGLE => 'Google',
            self::LINKEDIN => 'LinkedIn',
            self::GITHUB => 'GitHub',
            self::GITLAB => 'GitLab',
            self::BITBUCKET => 'Bitbucket',
            self::SLACK => 'Slack',
            self::TWITCH => 'Twitch',
        };
    }

    /**
     * Check if the provider supports OAuth 2.0.
     */
    public function supportsOAuth2(): bool
    {
        return match ($this) {
            self::TWITTER => false, // Twitter uses OAuth 1.0a
            default => true,
        };
    }

    /**
     * Get the official documentation URL for the provider.
     */
    public function getDocumentationUrl(): string
    {
        return match ($this) {
            self::FACEBOOK => 'https://developers.facebook.com/docs/facebook-login',
            self::TWITTER => 'https://developer.twitter.com/en/docs/authentication/oauth-1-0a',
            self::GOOGLE => 'https://developers.google.com/identity/protocols/oauth2',
            self::LINKEDIN => 'https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow',
            self::GITHUB => 'https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps',
            self::GITLAB => 'https://docs.gitlab.com/ee/api/oauth2.html',
            self::BITBUCKET => 'https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/',
            self::SLACK => 'https://api.slack.com/authentication/oauth-v2',
            self::TWITCH => 'https://dev.twitch.tv/docs/authentication',
        };
    }

    /**
     * Check if the provider requires state verification.
     */
    public function requiresState(): bool
    {
        return true;
    }

    /**
     * Get the default scopes for the provider.
     */
    public function getDefaultScopes(): array
    {
        return match ($this) {
            self::FACEBOOK => ['email', 'public_profile'],
            self::GOOGLE => ['email', 'profile'],
            self::GITHUB => ['read:user', 'user:email'],
            self::LINKEDIN => ['r_emailaddress', 'r_liteprofile'],
            self::GITLAB => ['read_user'],
            self::BITBUCKET => ['account'],
            self::SLACK => ['identity.basic', 'identity.email'],
            self::TWITCH => ['user:read:email'],
            self::TWITTER => [], // Twitter doesn't use scopes in OAuth 1.0a
        };
    }

    /**
     * Get all available provider values.
     */
    public static function getValues(): array
    {
        return array_column(self::cases(), 'value');
    }

    /**
     * Get all provider display names.
     */
    public static function getDisplayNames(): array
    {
        $names = [];
        foreach (self::cases() as $case) {
            $names[$case->value] = $case->getDisplayName();
        }
        return $names;
    }
}
