<?php

declare(strict_types=1);

namespace AndyDefer\PhpVo\Enums;

/**
 * Space Time Units Enum.
 *
 * @author Generated by Andy Defer
 */
enum SpaceTimeUnit: string
{
    // ==================== LENGTH (Base units and multiples) ====================
    case METRE = 'm';
    case KILOMETRE = 'km';
    case CENTIMETRE = 'cm';
    case MILLIMETRE = 'mm';
    case MICROMETRE = 'µm';
    case NANOMETRE = 'nm';

        // ==================== LENGTH (Annexes - Special units) ====================
    case ANGSTROM = 'Å';
    case NAUTICAL_MILE = 'M';
    case LIGHT_YEAR = 'ly';
    case ASTRONOMICAL_UNIT = 'ua';
    case PARSEC = 'pc';

        // ==================== AREA (Derived units) ====================
    case SQUARE_METRE = 'm²';
    case ARE = 'a';
    case HECTARE = 'ha';

        // ==================== VOLUME (Derived units) ====================
    case CUBIC_METRE = 'm³';
    case LITRE = 'L';

        // ==================== TIME (Base units and multiples) ====================
    case SECOND = 's';
    case MINUTE = 'min';
    case HOUR = 'h';
    case DAY = 'd';

        // ==================== SPEED (Derived units) ====================
    case METRE_PER_SECOND = 'm/s';
    case KILOMETRE_PER_HOUR = 'km/h';
    case KNOT = 'kn';

        // ==================== ACCELERATION (Derived units) ====================
    case METRE_PER_SQUARE_SECOND = 'm/s²';
    case GAL = 'Gal';

        // ==================== LOGARITHMIC QUANTITIES (Annex - Levels) ====================
    case NEPER = 'Np';
    case BEL = 'B';
    case DECIBEL = 'dB';

        // ==================== ANGLE (Derived units - mentioned in ISO 80000-3) ====================
    case RADIAN = 'rad';
    case DEGREE = '°';
    case ARC_MINUTE = "'";
    case ARC_SECOND = "''";
    case REVOLUTION = 'tr';

    public function isLengthUnit(): bool
    {
        return in_array($this, [
            self::METRE,
            self::KILOMETRE,
            self::CENTIMETRE,
            self::MILLIMETRE,
            self::MICROMETRE,
            self::NANOMETRE,
            self::ANGSTROM,
            self::NAUTICAL_MILE,
            self::LIGHT_YEAR,
            self::ASTRONOMICAL_UNIT,
            self::PARSEC
        ]);
    }

    public function isTimeUnit(): bool
    {
        return in_array($this, [
            self::SECOND,
            self::MINUTE,
            self::HOUR,
            self::DAY
        ]);
    }

    public function getConversionToBase(): ?float
    {
        return match ($this) {
            self::METRE => 1.0,
            self::KILOMETRE => 1000.0,
            self::CENTIMETRE => 0.01,
            self::MILLIMETRE => 0.001,
            self::MICROMETRE => 1e-6,
            self::NANOMETRE => 1e-9,
            self::ANGSTROM => 1e-10,
            self::NAUTICAL_MILE => 1852.0,
            self::LIGHT_YEAR => 9.4607304725808e15,
            self::ASTRONOMICAL_UNIT => 1.49597870700e11,
            self::PARSEC => 3.085677581491367e16,
            self::SECOND => 1.0,
            self::MINUTE => 60.0,
            self::HOUR => 3600.0,
            self::DAY => 86400.0,
            default => null,
        };
    }
}
